add deploy sonarqube doc
erda-project/docs pull request #197
Opened 2022-03-29 07:41 UTC by chengjoey

add doc for how to deploy a sonarqub server

2022-03-29 07:58 UTC, Effet requested changes

2022-03-29 07:58 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
这篇文章要不只是教他如何快速发起，要改成先整体介绍一下：
```
我们希望能够xxx，所以建议你先准备一个sonar，但是如果你想快速尝鲜，我们也帮助你快速发起xxx，所以本文后续会提供集中可选的方式：
1. x
2. x
3. x
```

再分几个小章节介绍分别如何准备 sonar

最后再来一个章节介绍如何配置和初始化sonar 的项目

2022-03-30 02:57 UTC, chengjoey commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
adjusted

2022-03-30 03:30 UTC, Effet requested changes

2022-03-30 03:30 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +3. 已有sonar服务，直接使用
顺序调整为：
1. 已有自建 sonar 服务
2. 没有
    a) 使用 saas (sonar cloud)
    b) 尝鲜试用【不建议生产】

2022-03-30 03:30 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +## 自建sonar
调整为 `可选方案` 的子章节，其底下的子章节变为子子章节。

“自建 sonar” 文案改下，类似于快速尝鲜啥的

2022-03-30 03:30 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +在需要的项目下新建一个应用用来部署自建的sonar，比如新建一个叫做`sonarqube`的应用
补充阐述一下，为什么要通过新建应用，为什么要写流水线，并反复强调一下只是为了快速尝鲜

2022-03-30 03:30 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
中间插一个子章节：“已有自建 sonar”，简单讲一下，如果已有的话，可以直接进入下一个大章节

2022-03-30 03:30 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
在这里插一个和“可选方案”同级的章节，讲下当 sonar 有了之后（不管是已有的，还是通过 cloud 还是通过尝鲜版搭建的）应该怎么配置，包括不仅限于怎么创建项目，生成 token 等，简单讲下就好，详情加一个官网的配置链接

2022-03-30 03:30 UTC, Effet commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +## 在erda使用自建sonar
文案可以改成 “开始为你的业务应用配置 sonar”

2022-03-30 06:06 UTC, chengjoey commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +3. 已有sonar服务，直接使用
adjusted

2022-03-30 06:06 UTC, chengjoey commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +## 在erda使用自建sonar
adjusted

2022-03-30 06:06 UTC, chengjoey commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
added

2022-03-30 06:06 UTC, chengjoey commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
added

2022-03-30 06:07 UTC, chengjoey commented on docs/2.0/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +在需要的项目下新建一个应用用来部署自建的sonar，比如新建一个叫做`sonarqube`的应用
added

2022-03-30 07:50 UTC, Effet requested changes

2022-03-30 07:50 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +# 如何准备sonar
标题可以改为：“在 Erda 中使用 SonarQube”

2022-03-30 07:50 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +## 可选方案
章节标题改为：“首先准备一个可用的 SonarQube 服务”

2022-03-30 07:50 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +              sonar: registry.cn-hangzhou.aliyuncs.com/dice-third-party/sonar:8.9.6
image 写到 dice.yml 更合适

2022-03-30 08:29 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +在使用SonarCloud或已有自建sonar服务的情况下，可跳过下面的临时 Sonar 实例章节，进行 [sonar配置](#sonarQube配置)
这里还是拆成两个章节为好，可以再稍微详细的讲一下大致的注意点，比如 cloud 的话多贴几个官方的链接引导一下

自建的话，也提供几个建议，比如自建有几种方式：纯人工运维、helm chart、docker 啥的

2022-03-30 08:29 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +3. 临时 Sonar 实例【不可用于真实使用场景】
这里也可以加下锚点链接

2022-03-30 08:29 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +## sonarQube配置
标题可以改为：“在 SonarQube 中创建项目和授权凭证（Token）”

2022-03-30 08:29 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
提供一个可以直接获得的 repo
:::
在这个 block 里讲一下：我们也提供了可以直接使用的代码仓库：【链接】
:::

2022-03-30 08:29 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +
中间再插一个章节：“准备工作”

内容大概从准备项目开始，准备资源、确保有集群（因为跑流水线部署都需要资源），以及要理解这些项目、集群的概念、理解项目-应用两级结构。

简单介绍，关键词都加个链接链到其他已有的文档

2022-03-30 08:29 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +## 首先准备一个可用的 SonarQube 服务
首先两字可以去掉

2022-04-01 07:27 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +2. [项目资源管理](../../../ecp/resource.md)
```
xxxx
1. yyy
2. zzz
```
的格式往往让人不知道要怎么动手，不妨写成一段顺序的话，这样会有连贯的感觉：

```
着手使用 sonar 前，你需要对 Erda 有一个初步的了解。Erda 是以项目和应用为中心【link？】来展开一系列功能的，所以你首先需要有一个项目【link 项目概念的介绍】，并且需要为此项目分配资源【link 资源概念的介绍，以及如何分配的 link】。

::: tip
请确保分配的资源满足和匹配应用构建的环境以及其他限制，我们发现有很多用户往往对此有所忽略而导致无法进行正常构建。具体详情请参看：【link 如何确保资源标签匹配实际诉求，可link到机器标签管理】
:::

如果你正打算创建一个全新的项目，我们建议你先阅读下面两篇：
1. [项目和应用创建](../../../quick-start/newbie.html#加入项目)
2. [项目资源管理](../../../ecp/resource.md)

如果你对如何管理项目资源有所疑惑，我们建议你继续阅读以下几篇：
1. xxx
2. yyy

如果你已经准备好项目，并正确进行了资源配置，那么请进入下面的章节【link】继续学习。
```

2022-04-01 07:27 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +我们也提供了可以直接使用的代码仓库: [代码示例](https://github.com/chengjoey/erda-sonarqube)
你也可以直接使用我们准备好的例子，免去从零调试的麻烦，代码仓库：

2022-04-01 09:20 UTC, chengjoey commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +2. [项目资源管理](../../../ecp/resource.md)
adjusted

2022-04-01 09:20 UTC, chengjoey commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +我们也提供了可以直接使用的代码仓库: [代码示例](https://github.com/chengjoey/erda-sonarqube)
adjusted

2022-04-01 11:01 UTC, Effet requested changes

2022-04-01 11:01 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +着手使用 sonar 前，你需要对 Erda 有一个初步的了解。Erda 是以 [项目和应用](../../../quick-start/premise.html) 为中心来展开一系列功能的，所以你首先需要有一个 [项目](../../../quick-start/premise.html#项目)，并且需要为此项目分配资源【[什么是集群](../../../quick-start/premise
太突兀了，分配资源后边突然出现了介绍集群？这个集群没有上下文的

2022-04-01 11:08 UTC, chengjoey commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +着手使用 sonar 前，你需要对 Erda 有一个初步的了解。Erda 是以 [项目和应用](../../../quick-start/premise.html) 为中心来展开一系列功能的，所以你首先需要有一个 [项目](../../../quick-start/premise.html#项目)，并且需要为此项目分配资源【[什么是集群](../../../quick-start/premise
adjusted

2022-04-01 11:11 UTC, Effet requested changes

2022-04-01 11:11 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +::: tip
在 tip 之前补充一下大概要做的事情，比如总共需要写两个文件，然后这两个文件大致是干啥的。

然后再接上这个 tip 比较顺滑

2022-04-01 11:54 UTC, Effet requested changes

2022-04-02 03:28 UTC, Effet requested changes

2022-04-02 03:28 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +新建应用后是为了编写`pipeline.yml`和`erda.yml`帮助我们快速的部署sonar服务，其中`pipeline.yml`帮助我们快速输出sonarQube服务制品【 [更多关于流水线](../../../dop/concepts/pipeline.html) 】,`erda.yml`让我们以声明的方式运行服务【 [更多关于erda.yml](../../../dop/concep
建好应用之后，我们需要编写....和...

2022-04-02 03:28 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +在使用`sonar action`时请选择2.0版本以支持自定义sonarQube服务，1.0版本仍旧是集成在erda中【 [1.0版本请查看](../../../dop/guides/qa-and-testing/sonar-report.html) 】
`1.0版本仍旧是集成在erda中` -> 若不指定版本，则默认为 1.0 版本

2022-04-02 03:28 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +            code_dir: ${{ dirs.git-checkout }}
这里展开讲一下参数的含义，可以直接在文件上备注。

然后再后面补充一段，如果需要做 quality gate check，要怎么配，quality gate 也可以补充一下官网的链接。并且这个例子可能还要再加一个打包任务在下面

2022-04-02 03:52 UTC, chengjoey commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +新建应用后是为了编写`pipeline.yml`和`erda.yml`帮助我们快速的部署sonar服务，其中`pipeline.yml`帮助我们快速输出sonarQube服务制品【 [更多关于流水线](../../../dop/concepts/pipeline.html) 】,`erda.yml`让我们以声明的方式运行服务【 [更多关于erda.yml](../../../dop/concep
adjusted

2022-04-02 03:53 UTC, chengjoey commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +在使用`sonar action`时请选择2.0版本以支持自定义sonarQube服务，1.0版本仍旧是集成在erda中【 [1.0版本请查看](../../../dop/guides/qa-and-testing/sonar-report.html) 】
adjusted

2022-04-02 03:53 UTC, chengjoey commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +            code_dir: ${{ dirs.git-checkout }}
added tips

2022-04-02 05:38 UTC, Effet requested changes

2022-04-02 05:38 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +3. [临时 Sonar 示例](#临时Sonar示例)【不可用于真实使用场景】
临时 Sonar 实例

2022-04-02 05:38 UTC, Effet commented on docs/next/manual/dop/guides/qa-and-testing/deploy-sonarqube.md
> +### 临时Sonar示例
临时Sonar实例

2022-04-02 06:15 UTC, Effet approved these changes

2022-04-02 06:15 UTC, merged