feat: add doc for pipeline queue
erda-project/docs pull request #246
Opened 2022-08-17 06:54 UTC by chengjoey

add doc for cicd pipeline queue

2022-08-17 06:57 UTC, chengjoey commented
#https://github.com/erda-project/erda/pull/5410

2022-08-18 08:42 UTC, sfwn requested changes

2022-08-18 08:42 UTC, sfwn commented on docs/next/manual/dop/guides/cicd-pipeline/pipeline-execution.md
> +当前CI/CD流水线没有绑定队列，因此当有同名的流水线在执行中的话，将会阻止当前流水线继续执行。想要执行当前流水线的话，
目前是这样的吗，还是会覆盖，取消前一条?
我记得是 应用流水线和项目流水线不同，需要说明清楚。

2022-08-18 08:42 UTC, sfwn commented on docs/next/manual/dop/guides/cicd-pipeline/pipeline-execution.md
> +因此在2.3版本往后，将为CI/CD流水线自动绑定队列，所有希望运行的流水线进入队列依次执行。
不是依次执行，是会根据一定策略执行，比如资源只够队列最后一条流水线执行，那么就不是依次了。

2022-08-18 08:42 UTC, sfwn commented on docs/next/manual/dop/guides/cicd-pipeline/pipeline-execution.md
> +默认绑定队列后，将可以有多条流水线同时运行，当队列满时，后面的流水线将处于排队状态中。
不一定是满，而是不满足执行条件，比如资源不够、已经达到最大并发度等。

2022-08-18 09:32 UTC, chengjoey commented on docs/next/manual/dop/guides/cicd-pipeline/pipeline-execution.md
> +当前CI/CD流水线没有绑定队列，因此当有同名的流水线在执行中的话，将会阻止当前流水线继续执行。想要执行当前流水线的话，
是这样的，如果已有同名的在执行，只能取消后才能接着执行

2022-08-18 09:44 UTC, chengjoey commented on docs/next/manual/dop/guides/cicd-pipeline/pipeline-execution.md
> +因此在2.3版本往后，将为CI/CD流水线自动绑定队列，所有希望运行的流水线进入队列依次执行。
已改

2022-08-18 09:44 UTC, chengjoey commented on docs/next/manual/dop/guides/cicd-pipeline/pipeline-execution.md
> +默认绑定队列后，将可以有多条流水线同时运行，当队列满时，后面的流水线将处于排队状态中。
已改

2022-09-07 07:27 UTC, huangzx618 approved these changes
/approve

2022-09-07 07:27 UTC, huangzx618 commented
/approve

2022-10-26 03:23 UTC, sfwn approved these changes

2022-10-26 03:23 UTC, merged